### ISSUE TITLE
[Bug]: GESTURE_HOLD_BEGIN/END event send when numpad is active

### ISSUE THREAD

**Issue by dfgweb** [asus-linux-drivers/asus-numberpad-driver#116]
### Describe the bug

After activated the numpad, I correctly got KEY events, but I also got POINTER_MOTION & GESTURE_HOLD_BEGIN/END events which are forwarded to current selected application (Emacs in my case), resulting in cursor move in addition of key press. So it isn't possible to use the numpad.

Without this driver running, when I tap on the touch in my Emacs windows, Emacs change cursor position in response to following events:
```
 event6   GESTURE_HOLD_BEGIN      +188.496s	1
 event6   GESTURE_HOLD_END        +188.516s	1
```

When this driver is running, and numpad is activated, I get these events:
```
-event6   POINTER_MOTION          +27.086s	 0.00/ -0.13 ( +0.00/ -1.00)
 event6   GESTURE_HOLD_BEGIN      +27.090s	1
 event6   POINTER_MOTION          +27.093s	 0.00/ -0.57 ( +0.00/ -2.00)
 event6   GESTURE_HOLD_END        +27.107s	1
-event20  KEYBOARD_KEY            +27.108s	*** (-1) pressed
 event20  KEYBOARD_KEY            +27.108s	*** (-1) released
```

The `GESTURE_HOLD_BEGIN/END` events should be filtered if numpad is enabled because it interact with application and result in cursor moved while typing.

Below, the full `libinput debug-events` output:
```
-event2   DEVICE_ADDED            Power Button                      seat0 default group1  cap:k
-event4   DEVICE_ADDED            Video Bus                         seat0 default group2  cap:k
-event0   DEVICE_ADDED            Lid Switch                        seat0 default group3  cap:S
-event1   DEVICE_ADDED            Power Button                      seat0 default group4  cap:k
-event14  DEVICE_ADDED            Logitech USB Receiver             seat0 default group5  cap:k
-event15  DEVICE_ADDED            Logitech USB Receiver Mouse       seat0 default group5  cap:p left scroll-nat scroll-button
-event16  DEVICE_ADDED            Logitech USB Receiver Consumer Control seat0 default group5  cap:kp scroll-nat
-event17  DEVICE_ADDED            Logitech USB Receiver System Control seat0 default group5  cap:k
-event18  DEVICE_ADDED            Generic USB Audio Consumer Control seat0 default group6  cap:kp scroll-nat
-event19  DEVICE_ADDED            Generic USB Audio                 seat0 default group6  cap:k
-event12  DEVICE_ADDED            USB2.0 HD UVC WebCam: USB2.0 HD   seat0 default group7  cap:k
-event13  DEVICE_ADDED            USB2.0 HD UVC WebCam: USB2.0 IR   seat0 default group7  cap:k
-event7   DEVICE_ADDED            ASUE140A:00 04F3:3134 Keyboard    seat0 default group8  cap:k
-event5   DEVICE_ADDED            ASUE140A:00 04F3:3134 Mouse       seat0 default group8  cap:p left scroll-nat scroll-button
-event6   DEVICE_ADDED            ASUE140A:00 04F3:3134 Touchpad    seat0 default group8  cap:pg  size 129x64mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on
-event8   DEVICE_ADDED            Asus WMI hotkeys                  seat0 default group9  cap:k
-event3   DEVICE_ADDED            AT Translated Set 2 keyboard      seat0 default group10 cap:k
-event20  DEVICE_ADDED            Asus Touchpad/Numpad              seat0 default group11 cap:kp left scroll-nat
-event3   KEYBOARD_KEY            +0.000s	KEY_LEFTMETA (125) pressed
 event3   KEYBOARD_KEY            +0.121s	*** (-1) pressed
 event3   KEYBOARD_KEY            +0.198s	KEY_LEFTMETA (125) released
 event3   KEYBOARD_KEY            +0.210s	*** (-1) released
-event20  KEYBOARD_KEY            +9.477s	*** (-1) pressed
 event20  KEYBOARD_KEY            +9.477s	*** (-1) released
-event6   POINTER_MOTION          +27.086s	 0.00/ -0.13 ( +0.00/ -1.00)
 event6   GESTURE_HOLD_BEGIN      +27.090s	1
 event6   POINTER_MOTION          +27.093s	 0.00/ -0.57 ( +0.00/ -2.00)
 event6   GESTURE_HOLD_END        +27.107s	1
-event20  KEYBOARD_KEY            +27.108s	*** (-1) pressed
 event20  KEYBOARD_KEY            +27.108s	*** (-1) released
-event6   GESTURE_HOLD_BEGIN      +27.725s	1
 event6   POINTER_MOTION          +27.735s	 0.00/ -0.58 ( +0.00/ -2.00)
 event6   POINTER_MOTION          +27.742s	 0.00/ -0.58 ( +0.00/ -2.00)
 event6   GESTURE_HOLD_END        +27.763s	1
-event20  KEYBOARD_KEY            +27.764s	*** (-1) pressed
 event20  KEYBOARD_KEY            +27.764s	*** (-1) released
-event6   GESTURE_HOLD_BEGIN      +28.452s	1
 event6   GESTURE_HOLD_END        +28.475s	1
-event20  KEYBOARD_KEY            +28.476s	*** (-1) pressed
 event20  KEYBOARD_KEY            +28.476s	*** (-1) released
-event6   GESTURE_HOLD_BEGIN      +31.106s	1
 event6   POINTER_MOTION          +31.140s	 0.00/ -0.27 ( +0.00/ -1.00)
 event6   POINTER_MOTION          +31.147s	 0.00/ -0.55 ( +0.00/ -2.00)
 event6   POINTER_MOTION          +31.154s	 0.00/ -1.02 ( +0.00/ -3.00)
 event6   GESTURE_HOLD_END        +31.168s	1
-event20  KEYBOARD_KEY            +31.169s	*** (-1) pressed
 event20  KEYBOARD_KEY            +31.170s	*** (-1) released
-event6   GESTURE_HOLD_BEGIN      +31.843s	1
 event6   POINTER_MOTION          +31.882s	 0.00/ -0.30 ( +0.00/ -1.00)
 event6   POINTER_MOTION          +31.889s	 0.00/ -0.55 ( +0.00/ -2.00)
 event6   GESTURE_HOLD_END        +31.903s	1
-event20  KEYBOARD_KEY            +31.904s	*** (-1) pressed
 event20  KEYBOARD_KEY            +31.904s	*** (-1) released
-event6   GESTURE_HOLD_BEGIN      +32.458s	1
 event6   POINTER_MOTION          +32.474s	-0.28/ -0.28 ( -1.00/ -1.00)
 event6   POINTER_MOTION          +32.481s	-0.30/ -0.59 ( -1.00/ -2.00)
 event6   GESTURE_HOLD_END        +32.495s	1
-event20  KEYBOARD_KEY            +32.496s	*** (-1) pressed
 event20  KEYBOARD_KEY            +32.496s	*** (-1) released
 event20  KEYBOARD_KEY            +40.937s	*** (-1) pressed
 event20  KEYBOARD_KEY            +40.937s	*** (-1) released
-event3   KEYBOARD_KEY            +54.837s	KEY_LEFTMETA (125) pressed
 event3   KEYBOARD_KEY            +55.840s	*** (-1) pressed
 event3   KEYBOARD_KEY            +55.970s	*** (-1) released
 event3   KEYBOARD_KEY            +56.040s	KEY_LEFTMETA (125) released
 event3   KEYBOARD_KEY            +57.191s	*** (-1) pressed
 event3   KEYBOARD_KEY            +57.310s	*** (-1) released
 event3   KEYBOARD_KEY            +58.046s	*** (-1) pressed
 event3   KEYBOARD_KEY            +58.593s	*** (-1) pressed
^C
```

### Expected behavior

Expect KEY events are sent and other event from touchpad are filtered out while numpad is active.

### Relevant log output

```shell
$ ./asus_touchpad.py "up5401ea" ""
INFO:asus-touchpad-numpad-driver:Detecting keyboard from string: "N: Name="AT Translated Set 2 keyboard""
INFO:asus-touchpad-numpad-driver:Set keyboard 3 from H: Handlers=sysrq kbd event3 leds
INFO:asus-touchpad-numpad-driver:Detecting touchpad from string: "N: Name="ASUE140A:00 04F3:3134 Touchpad""
INFO:asus-touchpad-numpad-driver:Set touchpad device id 1 from S: Sysfs=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-1/i2c-ASUE140A:00/0018:04F3:3134.0001/input/input9
INFO:asus-touchpad-numpad-driver:Set touchpad id 6 from H: Handlers=mouse1 event6
INFO:asus-touchpad-numpad-driver:Touchpad min-max: x 0-3987, y 0-1972
INFO:asus-touchpad-numpad-driver:Numpad min-max: x 200-3787, y 200-1892
Exception in thread Thread-1 (check_system_numlock_status):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
Exception in thread Thread-2 (check_touchpad_status_endless_cycle):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
TypeError: __main__.check_touchpad_status_endless_cycle() argument after * must be an iterable, not function
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-3 (check_numpad_automatical_disable_due_inactivity):
TypeError: __main__.check_system_numlock_status() argument after * must be an iterable, not function
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-4 (check_config_values_changes):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    self.run()
TypeError: __main__.check_numpad_automatical_disable_due_inactivity() argument after * must be an iterable, not function
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
TypeError: __main__.check_config_values_changes() argument after * must be an iterable, not function
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 699 y 1029
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 2155 y 958
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 3947 y 89
INFO:asus-touchpad-numpad-driver:Touched top_right_icon (numlock) in time: 1685533646.440159
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 3899 y 144
INFO:asus-touchpad-numpad-driver:The numpad numlock was pressed longer than the activation time: 2.5189781188964844
INFO:asus-touchpad-numpad-driver:Activation time: 1.0
INFO:asus-touchpad-numpad-driver:Un-touched with NumberPad activation top_right_icon (numlock) in time: 1685533648.9593747
INFO:asus-touchpad-numpad-driver:System numlock activated
INFO:asus-touchpad-numpad-driver:Numpad activated
WARNING: running xinput against an Xwayland server. See the xinput man page for details.
unable to find device ASUE140A:00 04F3:3134 Touchpad
ERROR:asus-touchpad-numpad-driver:b''
INFO:asus-touchpad-numpad-driver:Setting up for config file key: "enabled" with value: "True"
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 547 y 367
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 547 y 364
INFO:asus-touchpad-numpad-driver:Pressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP7:71
INFO:asus-touchpad-numpad-driver:Unpressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP7:71
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 1304 y 439
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 1304 y 435
INFO:asus-touchpad-numpad-driver:Pressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP8:72
INFO:asus-touchpad-numpad-driver:Unpressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP8:72
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 2032 y 423
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 2032 y 423
INFO:asus-touchpad-numpad-driver:Pressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP9:73
INFO:asus-touchpad-numpad-driver:Unpressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP9:73
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 514 y 818
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 514 y 812
INFO:asus-touchpad-numpad-driver:Pressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP4:75
INFO:asus-touchpad-numpad-driver:Unpressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP4:75
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 1274 y 807
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 1274 y 804
INFO:asus-touchpad-numpad-driver:Pressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP5:76
INFO:asus-touchpad-numpad-driver:Unpressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP5:76
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 1954 y 857
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 1952 y 854
INFO:asus-touchpad-numpad-driver:Pressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP6:77
INFO:asus-touchpad-numpad-driver:Unpressed numpad key
INFO:asus-touchpad-numpad-driver:KEY_KP6:77
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 3968 y 82
INFO:asus-touchpad-numpad-driver:Touched top_right_icon (numlock) in time: 1685533678.1081903
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 3918 y 114
INFO:asus-touchpad-numpad-driver:The numpad numlock was pressed longer than the activation time: 2.320267677307129
INFO:asus-touchpad-numpad-driver:Activation time: 1.0
INFO:asus-touchpad-numpad-driver:Un-touched with NumberPad activation top_right_icon (numlock) in time: 1685533680.4286492
INFO:asus-touchpad-numpad-driver:System numlock deactivated
INFO:asus-touchpad-numpad-driver:Numpad deactivated
WARNING: running xinput against an Xwayland server. See the xinput man page for details.
unable to find device ASUE140A:00 04F3:3134 Touchpad
ERROR:asus-touchpad-numpad-driver:b''
INFO:asus-touchpad-numpad-driver:Setting up for config file key: "enabled" with value: "False"
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 2809 y 798
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 1343 y 1354
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 2413 y 918
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 2055 y 1013
```

### Desktop

- Program version [e.g. 57c742a]: 958fb7855c522d946ed1a957ddf26277372cbcd8
- Distro [e.g. Arch Linux]: Ubuntu 22.04 LTS + Swaywm 1.7-1 (wayland)
- Kernel [e.g. 5.18.15.arch1-2]: 5.19.0-42-generic

**Comment by ldrahnik** [comment]
@dfgweb Hello there,
please, try to look to the config value `enabled_touchpad_pointer` described in `Readme.md`. Let me know change of this value solved your problem.

**Comment by ldrahnik** [comment]
@dfgweb Errors like this you will not see now in the log (`git pull master`).  ```Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
    self.run()
TypeError: __main__.check_numpad_automatical_disable_due_inactivity() argument after * must be an iterable, not function
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
TypeError: __main__.check_config_values_changes() argument after * must be an iterable, not function```

**Comment by dfgweb** [comment]
> @dfgweb Hello there, thank you for creating an issue. Please, take a look to the config value `enabled_touchpad_pointer` described in `Readme.md`. Let me know change of this value solved your problem.

After setting `enabled_touchpad_pointer` to 0 or 2, I don't have spurious `tap`, but I can't move pointer anymore while numpad activated. But numpad is really usable now. In mode 2, I can clic BTN_LEFT, MIDDLE & RIGHT, but without moving, not useful.

Same problem with `enabled_touchpad_pointer` to 1 than with the default value 3.

**Comment by ldrahnik** [comment]
@dfgweb When you use touchpad without this driver activated you have no `GESTURE_HOLD_BEGIN` and `GESTURE_HOLD_END`? I have but might be different for Wayland because I use X11.

**Comment by ldrahnik** [comment]
Is required issue owner activity can be reopened.
