### ISSUE TITLE
[Bug]: Touching percent % key on numpad result in exception

### ISSUE THREAD

**Issue by dfgweb** [asus-linux-drivers/asus-numberpad-driver#117]
### Describe the bug

Got the following exception when touching the '%' key in numpad:

Need to type Ctrl+C to exit driver.  Numpad still glowing. Then restarting it result in another exception.

Both in logs below.

Had to reset `enabled` to 0 in the configuration file.

### Expected behavior

- Key '%' is correctly handled and don't result in exception
- Numpad is automatically disabled on any exception so backlight switch off
- Restart the service don't fail when enabled=1 in config file

### Relevant log output

```shell
$ ./asus_touchpad.py "up5401ea" ""
INFO:asus-touchpad-numpad-driver:Detecting keyboard from string: "N: Name="AT Translated Set 2 keyboard""
INFO:asus-touchpad-numpad-driver:Set keyboard 3 from H: Handlers=sysrq kbd event3 leds
INFO:asus-touchpad-numpad-driver:Detecting touchpad from string: "N: Name="ASUE140A:00 04F3:3134 Touchpad""
INFO:asus-touchpad-numpad-driver:Set touchpad device id 1 from S: Sysfs=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-1/i2c-ASUE140A:00/0018:04F3:3134.0001/input/input9
INFO:asus-touchpad-numpad-driver:Set touchpad id 6 from H: Handlers=mouse1 event6
INFO:asus-touchpad-numpad-driver:Touchpad min-max: x 0-3987, y 0-1972
INFO:asus-touchpad-numpad-driver:Numpad min-max: x 200-3787, y 200-1892
...
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 3965 y 93
INFO:asus-touchpad-numpad-driver:Touched top_right_icon (numlock) in time: 1685548088.9081993
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 3934 y 139
INFO:asus-touchpad-numpad-driver:The numpad numlock was pressed longer than the activation time: 1.328244686126709
INFO:asus-touchpad-numpad-driver:Activation time: 1.0
INFO:asus-touchpad-numpad-driver:Un-touched with NumberPad activation top_right_icon (numlock) in time: 1685548090.2366278
INFO:asus-touchpad-numpad-driver:System numlock activated
INFO:asus-touchpad-numpad-driver:Numpad activated
INFO:asus-touchpad-numpad-driver:grab
INFO:asus-touchpad-numpad-driver:Setting up for config file key: "enabled" with value: "True"
INFO:asus-touchpad-numpad-driver:check_config_values_changes: detected internal change of config file -> do nothing -> would be deadlock
INFO:asus-touchpad-numpad-driver:Started new slot
INFO:asus-touchpad-numpad-driver:finger down at x 3628 y 1310
INFO:asus-touchpad-numpad-driver:Ended existing slot
INFO:asus-touchpad-numpad-driver:finger down at x 3628 y 1310
INFO:asus-touchpad-numpad-driver:Pressed numpad key
INFO:asus-touchpad-numpad-driver:%
ERROR:root:Listening touchpad events unexpectedly failed
Traceback (most recent call last):
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 942, in get_events_for_unicode_char
    key = EV_KEY.codes[int(key_code)]
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'KEY_KP2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 1692, in <module>
    listen_touchpad_events()
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 1567, in listen_touchpad_events
    pressed_numpad_key()
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 978, in pressed_numpad_key
    events = events + get_events_for_unicode_char(unicode_char)
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 947, in get_events_for_unicode_char
    key = EV_KEY.codes[int(key_code)]
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'KEY_KP2'
^CTraceback (most recent call last):
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 1700, in <module>
    thread.join()
  File "/usr/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt

$ ./asus_touchpad.py "up5401ea" ""
INFO:asus-touchpad-numpad-driver:Detecting keyboard from string: "N: Name="AT Translated Set 2 keyboard""
INFO:asus-touchpad-numpad-driver:Set keyboard 3 from H: Handlers=sysrq kbd event3 leds
INFO:asus-touchpad-numpad-driver:Detecting touchpad from string: "N: Name="ASUE140A:00 04F3:3134 Touchpad""
INFO:asus-touchpad-numpad-driver:Set touchpad device id 1 from S: Sysfs=/devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-1/i2c-ASUE140A:00/0018:04F3:3134.0001/input/input9
INFO:asus-touchpad-numpad-driver:Set touchpad id 6 from H: Handlers=mouse1 event6
INFO:asus-touchpad-numpad-driver:Touchpad min-max: x 0-3987, y 0-1972
INFO:asus-touchpad-numpad-driver:Numpad min-max: x 200-3787, y 200-1892
INFO:asus-touchpad-numpad-driver:Numpad activated
Traceback (most recent call last):
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 849, in <module>
    load_all_config_values()
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 828, in load_all_config_values
    local_numlock_pressed()
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 720, in local_numlock_pressed
    activate_numpad()
  File "/home/david/Sources/asus-numberpad-driver/./asus_touchpad.py", line 646, in activate_numpad
    grab()
NameError: name 'grab' is not defined
```

### Desktop

- Program version [e.g. 57c742a]: fedb464
- Distro [e.g. Arch Linux]: Ubuntu 22.04 + Swaywm 1.7-1
- Kernel [e.g. 5.18.15.arch1-2]: 5.19.0-42-generic

**Comment by ldrahnik** [comment]
@dfgweb 
> grab missing exception occurs only when enabled_touchpad_pointer set to 0 or 2. 

`git pull` latest master.

**Comment by ldrahnik** [comment]
@dfgweb 
> Got the following exception when touching the '%' key in numpad:

Exception using character % occurs using every keyboard layout or specific one? (EN, FR, DE, ..)

**Comment by ldrahnik** [comment]
@dfgweb 
> Restart the service don't fail when enabled=1 in config file

Please note here which exception is fired when is started driver and config file contains  `enabled=1`.

**Comment by ldrahnik** [comment]
@dfgweb Does work for your laptop fine btw brightness levels?

**Comment by ldrahnik** [comment]
Is required issue owner activity can be reopened.

**Comment by ldrahnik** [comment]
@dfgweb 

> Key '%' is correctly handled and don't result in exception

`git pull` latest master.
