### ISSUE TITLE
[Bug]: Followed instructions on ASUS ROG STRIX SCAR III G512LV but service is non-functioning.

### ISSUE THREAD

**Issue by DaanSelen** [asus-linux-drivers/asus-numberpad-driver#218]
### Describe the bug

Numpad does not activate with the touch button. Also the Systemd service fails without any useful error message.
I only changed the paths in the service file because the previous message was "could not find python3".

### Expected behavior

To have the red grid light up and the numpad functional.

### Relevant log output

```shell
dselen@DS-STRIX:/usr/lib/systemd/user$ systemctl status --user asus_numberpad_driver@$USER.service
● asus_numberpad_driver@dselen.service - Asus NumberPad Driver
     Loaded: loaded (/usr/lib/systemd/user/asus_numberpad_driver@.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2024-11-07 00:55:21 CET; 425ms ago
    Process: 9141 ExecStart=/usr/share/asus-numberpad-driver/.env/bin/python3 /usr/share/asus-numberpad-driver/numberpad.py up5401ea /usr/share/asus-numberpad-driver/ (code=exited, status=1/FAILURE)
   Main PID: 9141 (code=exited, status=1/FAILURE)
        CPU: 44ms
dselen@DS-STRIX:/usr/lib/systemd/user$ systemctl status --user asus_numberpad_driver@$USER.service
● asus_numberpad_driver@dselen.service - Asus NumberPad Driver
     Loaded: loaded (/usr/lib/systemd/user/asus_numberpad_driver@.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-11-07 00:55:23 CET; 1ms ago
   Main PID: 9146 (python3)
      Tasks: 1 (limit: 18822)
     Memory: 280.0K
        CPU: 0
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/app-asus_numberpad_driver.slice/asus_numberpad_driver@dselen.service
             └─9146 /usr/share/asus-numberpad-driver/.env/bin/python3 /usr/share/asus-numberpad-driver/numberpad.py up5401ea /usr/share/asus-numberpad-driver/

nov 07 00:55:23 DS-STRIX systemd[1108]: Started asus_numberpad_driver@dselen.service - Asus NumberPad Driver.
dselen@DS-STRIX:/usr/lib/systemd/user$ systemctl status --user asus_numberpad_driver@$USER.service
● asus_numberpad_driver@dselen.service - Asus NumberPad Driver
     Loaded: loaded (/usr/lib/systemd/user/asus_numberpad_driver@.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2024-11-07 00:55:23 CET; 956ms ago
    Process: 9146 ExecStart=/usr/share/asus-numberpad-driver/.env/bin/python3 /usr/share/asus-numberpad-driver/numberpad.py up5401ea /usr/share/asus-numberpad-driver/ (code=exited, status=1/FAILURE)
   Main PID: 9146 (code=exited, status=1/FAILURE)
        CPU: 41ms
dselen@DS-STRIX:/usr/lib/systemd/user$ systemctl status --user asus_numberpad_driver@$USER.service
● asus_numberpad_driver@dselen.service - Asus NumberPad Driver
     Loaded: loaded (/usr/lib/systemd/user/asus_numberpad_driver@.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2024-11-07 00:55:24 CET; 660ms ago
    Process: 9149 ExecStart=/usr/share/asus-numberpad-driver/.env/bin/python3 /usr/share/asus-numberpad-driver/numberpad.py up5401ea /usr/share/asus-numberpad-driver/ (code=exited, status=1/FAILURE)
   Main PID: 9149 (code=exited, status=1/FAILURE)
        CPU: 43ms
```

### Desktop

- Program version [e.g. 8669a89]
- Distro [e.g. Debian 12]
- Kernel [e.g. Linux DS-STRIX 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux]

**Comment by ldrahnik** [comment]
Please, attach driver logs.

**Comment by ldrahnik** [comment]
@DaanSelen Can be reopened.

**Comment by DaanSelen** [comment]
```
dselen@DS-STRIX:/var/log/asus-numberpad-driver$ cat install-07-11-2024-22-48-02.log 
Reading package lists...
Building dependency tree...
Reading state information...
ibus is already the newest version (1.5.27-5).
libevdev2 is already the newest version (1.13.0+dfsg-1).
curl is already the newest version (7.88.1-10+deb12u7).
xinput is already the newest version (1.6.3-1).
i2c-tools is already the newest version (4.3-2+b3).
python3-dev is already the newest version (3.11.2-1+b1).
python3-virtualenv is already the newest version (20.17.1+ds-1).
libxml2-utils is already the newest version (2.9.14+dfsg-1.3~deb12u1).
libxkbcommon-dev is already the newest version (1.5.0-1).
gcc is already the newest version (4:12.2.0-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

groupadd: group 'input' already exists
groupadd: group 'i2c' already exists
groupadd: group 'uinput' already exists
Added groups input, i2c, uinput, numberpad to current user
uinput module loaded
i2c-dev module loaded
uinput module added to auto loaded modules
Udev rules reloaded and triggered

The i2cdetect or i2ctransfer tool not found to proceed initial test whether any i2c device react like NumberPad

Default config will be autocreated during the first run and available for futher modifications here:
/usr/share/asus-numberpad-driver/numberpad_dev

created virtual environment CPython3.11.2.final.0-64 in 186ms
  creator CPython3Posix(dest=/usr/share/asus-numberpad-driver/.env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/dselen/.local/share/virtualenv)
    added seed packages: pip==23.0.1, setuptools==66.1.1, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Requirement already satisfied: pip in /usr/share/asus-numberpad-driver/.env/lib/python3.11/site-packages (23.0.1)
Collecting pip
  Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-24.3.1
Requirement already satisfied: setuptools in /usr/share/asus-numberpad-driver/.env/lib/python3.11/site-packages (66.1.1)
Collecting setuptools
  Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
Using cached setuptools-75.3.0-py3-none-any.whl (1.3 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 66.1.1
    Uninstalling setuptools-66.1.1:
      Successfully uninstalled setuptools-66.1.1
Successfully installed setuptools-75.3.0
Collecting libevdev (from -r requirements.txt (line 1))
  Using cached libevdev-0.11.tar.gz (27 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy (from -r requirements.txt (line 2))
  Using cached numpy-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting pyinotify (from -r requirements.txt (line 3))
  Using cached pyinotify-0.9.6.tar.gz (60 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting python-xlib (from -r requirements.txt (line 4))
  Using cached python_xlib-0.33-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting smbus2 (from -r requirements.txt (line 5))
  Using cached smbus2-0.5.0-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting pyasyncore (from -r requirements.txt (line 6))
  Using cached pyasyncore-1.0.4-py3-none-any.whl.metadata (3.7 kB)
Collecting pywayland (from -r requirements.txt (line 7))
  Using cached pywayland-0.4.18-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Collecting xkbcommon<1.1 (from -r requirements.txt (line 8))
  Using cached xkbcommon-1.0.1.tar.gz (79 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting systemd-python (from -r requirements.txt (line 9))
  Using cached systemd-python-235.tar.gz (61 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting six>=1.10.0 (from python-xlib->-r requirements.txt (line 4))
  Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting cffi>=1.12.0 (from pywayland->-r requirements.txt (line 7))
  Using cached cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.12.0->pywayland->-r requirements.txt (line 7))
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Downloading numpy-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 9.4 MB/s eta 0:00:00
Downloading python_xlib-0.33-py2.py3-none-any.whl (182 kB)
Downloading smbus2-0.5.0-py2.py3-none-any.whl (11 kB)
Downloading pyasyncore-1.0.4-py3-none-any.whl (10 kB)
Downloading pywayland-0.4.18-cp311-cp311-manylinux_2_28_x86_64.whl (836 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 836.1/836.1 kB 8.4 MB/s eta 0:00:00
Using cached cffi-1.17.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (467 kB)
Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Building wheels for collected packages: libevdev, pyinotify, xkbcommon, systemd-python
  Building wheel for libevdev (setup.py): started
  Building wheel for libevdev (setup.py): finished with status 'done'
  Created wheel for libevdev: filename=libevdev-0.11-py3-none-any.whl size=23836 sha256=37c379e47a41fd4ebe6b9a2b890a4694fde0c6a59b0dee58b72a7e47fc34b109
  Stored in directory: /home/dselen/.cache/pip/wheels/4e/29/79/d73742baf28a266ad21cd7808be07cf4925aee11eda949b943
  Building wheel for pyinotify (setup.py): started
  Building wheel for pyinotify (setup.py): finished with status 'done'
  Created wheel for pyinotify: filename=pyinotify-0.9.6-py3-none-any.whl size=25342 sha256=eae6ebbcb2edbecb30bc75d7868381d2ba55c8f94afe8f48e114f5d84ae8a76c
  Stored in directory: /home/dselen/.cache/pip/wheels/61/5f/c5/4c20d068f36a653907eeec8dfea850f191031229e0adbdba66
  Building wheel for xkbcommon (pyproject.toml): started
  Building wheel for xkbcommon (pyproject.toml): finished with status 'done'
  Created wheel for xkbcommon: filename=xkbcommon-1.0.1-cp311-cp311-linux_x86_64.whl size=95633 sha256=b60354e0bd92d5506adfebcaa871889cfe647495b1cb3c48be4a9a92498fa32a
  Stored in directory: /home/dselen/.cache/pip/wheels/8a/2e/ce/3e69a050ee7e0bf38488fcf81d67593679d346f7e91d1b39b4
  Building wheel for systemd-python (setup.py): started
  Building wheel for systemd-python (setup.py): finished with status 'done'
  Created wheel for systemd-python: filename=systemd_python-235-cp311-cp311-linux_x86_64.whl size=152967 sha256=3044a2b6a1a39732f3ae059d55ae23d857c1c1b6a977936da50721ebb5c0820a
  Stored in directory: /home/dselen/.cache/pip/wheels/13/77/24/4266dc1d98e2672f5575d49b15070d5a6274e2e977fbf50146
Successfully built libevdev pyinotify xkbcommon systemd-python
Installing collected packages: systemd-python, smbus2, pyinotify, pyasyncore, six, pycparser, numpy, libevdev, python-xlib, cffi, xkbcommon, pywayland
Successfully installed cffi-1.17.1 libevdev-0.11 numpy-2.1.3 pyasyncore-1.0.4 pycparser-2.22 pyinotify-0.9.6 python-xlib-0.33 pywayland-0.4.18 six-1.16.0 smbus2-0.5.0 systemd-python-235 xkbcommon-1.0.1



NumberPad layout

The driver will try to find the appropriate keys for each field of the layout that can be successfully sent. Key modifiers are supported. When the appropriate key cannot be found then the field will be sent using the Unicode shortcut (usually Ctrl+Shift+U+<0-F>).

Photos of all layouts can be found here https://github.com/asus-linux-drivers/asus-numberpad-driver#layouts.

Select layout:

1) b7402.py            3) g513.py            5) gx551.py           7) up5401ea-3145.py   9) ux433fa.py        11) Quit
2) e210ma.py           4) g533.py            6) gx701.py           8) up5401ea.py       10) ux581l.py
Please enter your choice 
Selected key layout: g513

Systemctl service

Do you want install systemctl service? [y/N]
LAYOUT_NAME: g513
CONFIG_FILE_DIR_PATH: /usr/share/asus-numberpad-driver

env var DISPLAY: :1
env var WAYLAND_DISPLAY: wayland-0
env var AUTHORITY: /run/user/1000/xauth_YtJoww
env var XDG_RUNTIME_DIR: /run/user/1000
env var DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
env var XDG_SESSION_TYPE: wayland

ERROR LOG FILE: /var/log/asus-numberpad-driver/error.log

Unfortunatelly you will not be able use feature: Disabling Touchpad (e.g. Fn+special key) disables NumberPad aswell, at this moment is supported only X11
Asus numberpad driver service placed
Systemctl daemon reloaded
Asus numberpad driver service enabled
Asus numberpad driver service started

External keyboard

This is a predefined rule for changing the configuration when an external keyboard is connected/disconnected.

The application of this rule results in the following changes if an external keyboard is connected:

 - Numlock key does not activate NumberPad (config value is set to sys_numlock_enables_numpad=0)
 - Numberpad disactivation does not disable Numlock (config value is set to numpad_disables_sys_numlock=0)

In summary when an external keyboard is connected then NumberPad activation is not linked to Numlock state and vice versa.

Do you want install the rule for external keyboard? [y/N]
Calculator app

Do you want try to install toggling script for XF86Calculator key? [y/N]
Power supply saver

By default is idle functionality disabled and may be manually enabled in config file later. Or by installing this rule can be enabled by every detected change of power supply mode to battery mode.

Idle mode is configured to be enabled after 10s of inactivity and to decrease 30% of brightness.

Do you want install the rule for idle functionality? [y/N]
Rule 80-numberpad-power-supply applied
Udev rules reloaded and triggered

Installation finished succesfully

Reboot is required. Do you want reboot now? [y/N]
dselen@DS-STRIX:/var/log/asus-numberpad-driver$
```
Following the logs

**Comment by DaanSelen** [comment]
```
dselen@DS-STRIX:~/asus-numberpad-driver$ export PATH=/usr/sbin:$PATH
dselen@DS-STRIX:~/asus-numberpad-driver$ bash install_device_check.sh 
Testing interface i2c-1: success (adr 0x38)
The detection was successful. Touchpad with NumberPad found: i2c-1
```

**Comment by ldrahnik** [comment]
@DaanSelen What have you changed and where for `python3`? Because I see service from yesterday as `running` and `python3` set up to virtual environment as usually that means `/usr/share/asus-numberpad-driver/.env/bin/python3`.

**Comment by ldrahnik** [comment]
@DaanSelen Do you hold the icon for at least 1s?

**Comment by ldrahnik** [comment]
> 
```
dselen@DS-STRIX:~/asus-numberpad-driver$ export PATH=/usr/sbin:$PATH
dselen@DS-STRIX:~/asus-numberpad-driver$ bash install_device_check.sh 
Testing interface i2c-1: success (adr 0x38)
The detection was successful. Touchpad with NumberPad found: i2c-1
```

@DaanSelen https://github.com/asus-linux-drivers/asus-numberpad-driver/commit/18acef39f5f34391082cde54bdbe51651254a212

**Comment by JorchMantilla** [comment]
hello, same here. Part of a log file says:

Collecting pywayland (from -r requirements.txt (line 7))
  Downloading pywayland-0.4.18.tar.gz (247 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running dist_info
      creating /tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info
      writing /tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info/entry_points.txt
      writing requirements to /tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info/requires.txt
      writing top-level names to /tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info/top_level.txt
      writing manifest file '/tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-modern-metadata-ukihghh0/pywayland.egg-info/SOURCES.txt'
      creating '/tmp/pip-modern-metadata-ukihghh0/pywayland-0.4.18.dist-info'
      Traceback (most recent call last):
        File "/usr/share/asus-numberpad-driver/.env/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/share/asus-numberpad-driver/.env/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/share/asus-numberpad-driver/.env/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 376, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 175, in <module>
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 999, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/command/dist_info.py", line 98, in run
          bdist_wheel = self.get_finalized_command('bdist_wheel')
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 303, in get_finalized_command
          cmd_obj.ensure_finalized()
          ~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-0jnf4bv6/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
          ~~~~~~~~~~~~~~~~~~~~~^^
        File "<string>", line 78, in finalize_options
      AssertionError: Specified Wayland protocol file, /usr/share/wayland/wayland.xml, does not exist please specify valid protocol file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by JorchMantilla** [comment]
[install-08-11-2024-15-41-46.log](https://github.com/user-attachments/files/17684055/install-08-11-2024-15-41-46.log)

**Comment by DaanSelen** [comment]
> Systemd

Okay after 1 full second it works! I am going to look to shortening this.

**Comment by ldrahnik** [comment]
@JorchMantilla Try the lower version of Python (I use it without any problem `3.10.12`) and in case still does not work please create another issue. Unfortunately for my distribution does not work installing Python `3.13-dev` using `pyenv`.
